### PR TITLE
Optionally avoid auto ticks() processing.

### PR DESCRIPTION
**Pull request by TommyC81**
Configurable (via #define) avoidance of the processing of ticks() on every tick() call.

### CODE REVIEW

**Comment by philj404** [comment]
When/why would you want to set this #define ARDUINO_TIMER_NO_TICK_REPORT?

Can you document it in the README.md?  (That reminds me -- I need to update README.md in my pull request too! Not too late yet.)

I want to make sure we keep the "easy to use" goal with this library.

**Comment by contrem** [comment]
An alternate implementation of this is at [mc/ticks-optional](https://github.com/contrem/arduino-timer/tree/mc/ticks-optional). It allows for the following:

```cpp
loop {
    timer.tick<void>(); // avoids ticks() calculation
}
```

[Originally](https://github.com/contrem/arduino-timer/issues/1#issuecomment-429452893) I had planned to make *ticks* its own function for this exact reason. Maybe in a future major version update *tick()* will default to return void as initially planned, but for now this is a backwards compatible workaround that doesn't require compile time defines, while still keeping compile time benefits.

**Comment by philj404** [comment]
That mc/ticks-optional branch looks good.  But you should probably update the README.md to make it clear how to use it.

**Comment by TommyC81** [comment]
Agreed, that is a better solution and avoids a "define" - ie you can still use the ticks return for other arduino-timers.

Maybe consider a major version update after this to make the default return being void and require the use of a separate function to get ticksToNextTask(). Also agreed that the function naming to get the ticks can be more descriptive.

Many thanks for the library!

**Comment by contrem** [comment]
Optional *ticks()* processing via `timer.tick<void>()` merged in 9f6f82b296b1359e01f0df9e585954813c053bcd.

**Pull request closed without merging**
